---
title: "pratica_modulo_1"
output: html_document
date: "2024-03-21"
---

Pratica para examinar dados de diferentes tipos em R

Usaremos alguns conjuntos de dados ja distribuidos com o R:
cars, mtcars, iris, 
nosso primeiro objetivo sera entender quais os tipos de variaveis presentes
vamos carregar primeiro o conjunto mtcars

````{R}
data(mtcars)
str(mtcars)
````
Todas as variaveis sao numericas. Entretanto algumas na realidade sao
categoricas, ou seja o numero na realidade se refere a uma classe
quais variaveis sao categoricas nesta amostra?
vamos recodifica-las usando a funcao as,factor
substitua o x pela variavel de interesse e aplique a funcao

mtcars$x <- as.factor(mtcars$x)

Vamos fazer alguns graficos
barplot: grafico de barras , frequencias de observacoes das variaveis categoricas

histogram:  distribuicao de frequencias para variaveis continuas

boxplot:  como visualizar variaveis categoricas e continuas simultaneamente

grafico x y ou grafico de dispersao - visualizar variaveis continuas

o R tem funcoes para fazer estes graficos ou também podemos usar o pacote ggplot2 que tem muita flexibilidade para fazer todos os tipos de graficos

Sugiro examinar o site R graph gallery que tem exemplos de gráficos e os scripts R para fazê-los:

https://r-graph-gallery.com/



Para nosso primeiro exemplo vamos usar um conjunto de dados com características de vários modelos de carros vendidos nos EUA. 

````{R}

library(ggplot2)
mtcars$gear <- as.factor(mtcars$gear)


# vamos fazer um barplot com o número de modelos que tem 3, 4, ou 5 marchas:
ggplot(mtcars, aes(x = gear)) + geom_bar()

# Em seguida vamos fazer um histograma, com número de modelos para milhas por galao:
milhagem <- mtcars$mpg
hist(milhagem)

#agora vamos fazer um boxplot de milhagem por marchas

boxplot(mpg ~ gear, data = mtcars, xlab = "Numero de marchas",
        ylab = "Milhas por Galao", main = "Milhagem")

````
como fazer legendas:
http://www.sthda.com/english/wiki/add-legends-to-plots-in-r-software-the-easiest-way

Finalmente, vamos fazer um grafico de dispersao:
escolha 2 variaveis numericas x e y
use o comando plot(x,y) para ver a relacao entre elas
